Menus support any controller
wiiu-env/AutobootModule pull request #33
Opened 2023-06-06 16:01 UTC by Andrew1Hawes

Also added KPADRead to the check to force open the menu. Of course it's unusable because the controllers don't connect quick enough, but the infrastructure's there for when we figure something out.

Fixes #23 
Semi-fixes #9 - you need to have autobooting disabled

2023-06-07 07:13 UTC, Andrew1Hawes commented
Just noticed I forgot to move everything into a function.

2023-06-09 00:04 UTC, Andrew1Hawes commented
@Maschell should be all done

2023-06-13 11:47 UTC, Maschell requested changes
Looking good so far. Can you fix `getInput` and move all input related functions into a new file (e.g. `InputUtils.h`)?

2023-06-13 11:47 UTC, Maschell commented on source/MenuUtils.cpp
> +    VPADRead(VPAD_CHAN_0, &vpadStatus, 1, &vpadError);
The return value of VPADRead is ignored and `vpadError` is not initalized. `inputData` also needs to be initalized!

Maybe do something like this:

```
VPADStatus vpadStatus {};
KPADStatus kpadStatus {};
InputData inputData {};
KPADError kpadError = KPAD_ERROR_UNINITIALIZED;
VPADReadError vpadError = VPAD_READ_UNINITIALIZED;
if (VPADRead(VPAD_CHAN_0, &vpad, 1, &vpadError) == 1 && vpadError == VPAD_READ_SUCCESS) {
    inputData.trigger = vpadStatus.trigger;
    inputData.hold    = vpadStatus.hold;
    inputData.release = vpadStatus.release;
}
```

2023-06-14 12:06 UTC, Maschell commented
I'll gonna do the fixes myself and then merge

2023-06-14 15:43 UTC, Maschell commented
Will be reopend and merged

2023-06-14 15:43 UTC, closed without merging